// Données des articles du portfolio
// Pour ajouter un article :
// 1) Dépose l'image dans assets/images/articles/
// 2) Ajoute un objet ci-dessous avec id unique, title, image (chemin relatif), excerpt, body (tableau de paragraphes ou sous-titres)

const articlesData = [
    {
        id: 'article-1',
        title: 'Pourquoi tant de projets informatiques échouent avant même la première ligne de code',
        image: 'assets/images/articles/projets informatiques echouent.png',
        excerpt: 'Pourquoi tant de projets informatiques échouent avant même la première ligne de code',
        category: 'Gouvernance produit',
        date: '2025-12-10',
        body: [
            'De nombreux projets sont fragilisés bien avant le démarrage du développement.',
            'L’échec prend souvent racine dans la phase de cadrage initial.',
            'Les objectifs sont imprécis, les priorités mal hiérarchisées et les contraintes métier sous-estimées.',
            'Le besoin réel est rarement formalisé de manière exploitable.',
            'Les choix techniques arrivent trop tôt, sans vision globale ni scénario d’évolution.',
            'Le périmètre évolue sans règles claires, créant des attentes contradictoires.',
            'Le projet progresse, mais sans direction stable.',
            'Le code devient alors une tentative d’adaptation permanente.',
            'Ce n’est pas un problème de compétences techniques, mais de décisions amont.',
            'Un projet bien cadré réduit les risques avant même d’écrire la première ligne de code.'
        ]
    },
    {
        id: 'article-2',
        title: 'Ce qui fait réellement démarrer un projet IT sur de bonnes bases',
        image: 'assets/images/articles/demarrer-un-projet-ITsur-de-bonnes-bases.png',
        excerpt: 'Ce qui fait réellement démarrer un projet IT sur de bonnes bases',
        category: 'Pilotage projet',
        date: '2026-01-13',
        body: [
            'Un projet IT démarre avant tout par une compréhension partagée.',
            'Tout commence par une définition claire du problème à résoudre.',
            'Les objectifs doivent être compréhensibles, mesurables et alignés entre les parties prenantes.',
            'Le besoin métier gagne à être traduit en exigences concrètes et priorisées.',
            'Un démarrage solide repose sur un périmètre défini et maîtrisé.',
            'Les contraintes doivent être identifiées dès le départ.',
            'Les rôles et responsabilités doivent être clairement établis.',
            'Les décisions efficaces s’appuient sur des éléments factuels.',
            'La vision produit guide les choix techniques.',
            'La technologie intervient comme un outil au service de cette vision.',
            'Un cadrage structuré facilite les arbitrages et sécurise l’exécution.',
            'Il améliore durablement la qualité du projet.'
        ]
    },
    {
        id: 'article-3',
        title: 'Ce que les cahiers des charges devraient toujours contenir',
        image: 'assets/images/articles/Ce que les cahiers des charges devraient toujours contenir.png',
        excerpt: 'Ce que les cahiers des charges devraient toujours contenir',
        category: 'Cadrage',
        date: '2026-01-20',
        body: [
            'Un cahier des charges sert avant tout à créer une compréhension commune.',
            '- Dans de nombreux projets, il se limite à une liste de fonctionnalités.',
            '- Les objectifs réels, les contraintes et les priorités restent implicites.',
            '- Résultat : chacun interprète le document selon son propre point de vue.',
            '',
            'Un bon cahier des charges commence par le problème à résoudre, pas par la solution.',
            '- Il précise les objectifs attendus, les indicateurs de succès et les contraintes métier.',
            '- Il définit clairement le périmètre, les hypothèses et les dépendances.',
            "- Les règles d'évolution, de validation et d'arbitrage y ont aussi leur place.",
            '',
            'La technique peut alors être choisie en connaissance de cause.',
            '- Le projet gagne en lisibilité, en cohérence et en prévisibilité.',
            "- Un cahier des charges incomplet crée de l'incertitude dès le départ.",
            '- Un cahier des charges structuré devient un véritable outil de pilotage.'
        ]
    },
    {
        id: 'article-4',
        title: 'Les décisions non techniques qui influencent le succès d\'un projet',
        image: 'assets/images/articles/Décisions_cles_hors_technique.png',
        excerpt: 'Les décisions non techniques qui influencent le succès d\'un projet',
        category: 'Gouvernance produit',
        date: '2026-01-27',
        body: [
            'La réussite d\'un projet ne dépend pas uniquement de la technologie.',
            '',
            '- Sur le terrain, les écarts apparaissent souvent avant même les choix techniques.',
            '- Les priorités sont parfois floues, les responsabilités mal définies et les arbitrages retardés.',
            '- Les contraintes métier, budgétaires ou organisationnelles sont sous-estimées.',
            '',
            '- Un projet progresse lorsque les objectifs sont clairs et partagés.',
            '- Lorsque les rôles sont définis et les décisions assumées.',
            '- Lorsque le périmètre est maîtrisé et les changements encadrés.',
            '- Lorsque la communication entre métiers et équipes techniques est continue.',
            '',
            '- La technique s\'adapte ensuite à ce cadre.',
            '- Sans ces décisions amont, même la meilleure architecture peine à tenir.',
            '',
            '- Le succès d\'un projet repose d\'abord sur la qualité des décisions non techniques.',
            '',
            '- Selon vous, laquelle de ces décisions est la plus déterminante dans un projet IT ?'
        ]
    },
    {
        id: 'article-5',
        title: 'Comprendre la dette technique avant qu\'elle ne devienne un problème',
        image: 'assets/images/articles/dette-technique.png',
        excerpt: 'Comprendre la dette technique avant qu\'elle ne devienne un problème',
        category: 'Qualité logicielle',
        date: '2026-02-03',
        body: [
            'La dette technique n\'apparaît jamais par hasard.',
            '',
            'Elle s\'installe progressivement, souvent sous l\'effet de contraintes de délai ou de budget.',
            'Des choix rapides, des compromis temporaires et des contournements s\'accumulent.',
            'À court terme, le projet avance. À long terme, la complexité augmente.',
            '',
            'La dette technique n\'est pas uniquement du code mal écrit.',
            'Elle concerne aussi l\'architecture, la documentation, les tests et les décisions repoussées.',
            'Chaque ajout devient plus coûteux, chaque correction plus risquée.',
            '',
            'Comprendre cette dette permet de la piloter.',
            'Identifier ce qui peut être différé et ce qui doit être traité rapidement est essentiel.',
            'Le refactoring devient alors un investissement, pas une perte de temps.',
            '',
            'Ignorer la dette technique finit toujours par ralentir le projet.',
            'La maîtriser permet de préserver la qualité et la capacité d\'évolution.'
        ]
    },
    {
        id: 'article-6',
        title: 'Front-end moderne : performance, UX et frameworks orientés production',
        image: 'assets/images/articles/Frontend-Moderne.jpg',
        excerpt: 'Front-end moderne : performance, UX et frameworks orientés production',
        category: 'Performance front-end',
        date: '2026-02-10',
        body: [
            'Le front-end ne se limite plus à afficher une interface.',
            '',
            'Sur de nombreux projets, les difficultés apparaissent après la mise en ligne.',
            'Temps de chargement instables, interactions peu fluides, dette JavaScript croissante.',
            'La complexité ne vient pas du design, mais des choix techniques initiaux.',
            '',
            'Les frameworks modernes répondent à ces enjeux en plaçant la production au centre.',
            'Rendu côté serveur, génération statique, gestion fine de l\'hydratation.',
            'Moins de JavaScript inutile, plus de performance perçue.',
            'Une meilleure maîtrise des Core Web Vitals et de l\'expérience utilisateur réelle.',
            '',
            'Un front-end efficace s\'appuie sur des décisions mesurables.',
            'Choisir un framework, c\'est d\'abord choisir un mode de rendu et une stratégie de performance.',
            'L\'UX devient alors une conséquence directe de l\'architecture.',
            '',
            'Aujourd\'hui, le front-end est un sujet d\'ingénierie autant que d\'interface.',
            'Les projets durables sont ceux qui traitent la performance comme une exigence de départ.'
        ]
    },
    {
        id: 'article-7',
        title: 'Backend moderne : robustesse, scalabilité et architecture orientée production',
        image: 'assets/images/articles/Backend-moderne.jpg',
        excerpt: 'Backend moderne : robustesse, scalabilité et architecture orientée production',
        category: 'Architecture backend',
        date: '2026-02-17',
        body: [
            'Un backend efficace ne se juge pas à la complexité de son architecture.',
            '',
            'Sur le terrain, beaucoup d\'applications fonctionnent en environnement de test, mais montrent leurs limites en production.',
            'Temps de réponse irréguliers, endpoints mal structurés, montée en charge imprévue.',
            'La difficulté ne vient pas du langage choisi, mais de la manière dont le système a été pensé.',
            '',
            'Un backend moderne repose d\'abord sur des API claires et cohérentes.',
            'Contrats bien définis, gestion explicite des erreurs, versionnement maîtrisé.',
            'La scalabilité n\'est pas un ajout tardif, mais une contrainte intégrée dès la conception.',
            '',
            'L\'architecture doit rester lisible.',
            'Monolithe modulaire, microservices ou serverless : le choix dépend du contexte, pas de la tendance.',
            'Ce qui compte, c\'est la capacité à observer, mesurer et ajuster en production.',
            '',
            'Un backend orienté production privilégie la robustesse, la performance mesurable et la simplicité maîtrisée.',
            'La sophistication inutile devient rapidement une dette.',
            '',
            'Un système backend réussi est celui qui reste stable lorsque l\'usage réel commence.'
        ]
    },
    {
        id: 'article-8',
        title: 'De la page statique aux architectures hybrides : 30 ans d\'évolution du front-end et du back-end',
        image: 'assets/images/articles/Back-front historique.jpg',
        excerpt: 'De la page statique aux architectures hybrides : 30 ans d\'évolution du front-end et du back-end',
        category: 'Histoire du web',
        date: '2026-02-24',
        body: [
            'La séparation entre front-end et back-end n\'a pas été une décision immédiate.',
            'Elle s\'est construite progressivement, au rythme des avancées technologiques du web.',
            '',
            'En 1989–1991, Tim Berners-Lee conçoit le World Wide Web au CERN.',
            'Le modèle est simple : un serveur envoie un document HTML, le navigateur l\'affiche.',
            'L\'architecture est centralisée, sans logique côté client.',
            '',
            'Milieu des années 1990 : le web devient dynamique.',
            '- PHP apparaît en 1995',
            '- ASP est lancé en 1996',
            '- Java (1995) s\'impose côté serveur',
            '',
            'Les pages sont désormais générées à la volée à partir de bases de données.',
            'Le back-end structure l\'application. Le front-end reste essentiellement déclaratif.',
            '',
            'Années 2005–2010 : rupture majeure.',
            'L\'AJAX (popularisé vers 2005) permet des échanges asynchrones.',
            'Puis émergent les frameworks JavaScript :',
            '- AngularJS en 2010',
            '- React en 2013',
            '- Vue.js en 2014',
            'Le navigateur devient une plateforme d\'exécution.',
            'Les applications front-end gèrent l\'état, les routes, les interactions complexes.',
            'Les API REST se généralisent.',
            'La séparation front-end / back-end devient une stratégie d\'architecture.',
            '',
            'À partir de 2016–2020, nouvelle évolution.',
            'Les limites des SPA lourdes apparaissent : performance, SEO, dette JavaScript.',
            'Des frameworks hybrides émergent :',
            '- Next.js (2016)',
            '- Remix (2020)',
            '- Astro (2021)',
            'Ils combinent rendu serveur, génération statique et hydratation partielle.',
            'La séparation ne disparaît pas, mais elle devient plus fine et mieux orchestrée.',
            '',
            'En trois décennies, l\'architecture web est passée :',
            '- du serveur centralisé',
            '- à la séparation stricte client / API',
            '- puis à des modèles hybrides orientés performance et production',
            '',
            'L\'histoire montre une constante :',
            'les choix d\'architecture évoluent pour répondre aux contraintes réelles d\'usage.',
            '',
            'Comprendre cette trajectoire permet de concevoir des systèmes cohérents aujourd\'hui,',
            'non pas en suivant une tendance, mais en s\'appuyant sur l\'expérience accumulée du web.'
        ]
    },
    {
        id: 'article-9',
        title: 'Intégrer la sécurité dès la conception d\'une application',
        image: 'assets/images/articles/Sécurité dès la conception.png',
        excerpt: 'Intégrer la sécurité dès la conception d\'une application',
        category: 'Sécurité',
        date: '2026-03-03',
        body: [
            '« Chef, la nouvelle application est prête ! Elle va hyper vite, le design est incroyable, on va tout casser !',
            '— Super ! Et pour la sécurité, on est bons ?',
            '— Ah... la sécurité... On va dire qu\'on rajoutera les freins en roulant, au prochain sprint ! »',
            '',
            'Ça vous fait sourire ? Pourtant, c\'est encore une réalité trop fréquente.',
            '',
            'La sécurité ne devrait jamais être une correction de fin de projet.',
            '',
            'Sur le terrain, elle est encore trop souvent traitée après le développement.',
            'Audit tardif, correctifs urgents, dette de sécurité accumulée.',
            'Le coût devient alors technique, financier et réputationnel.',
            '',
            'Intégrer la sécurité dès la conception change la trajectoire.',
            'Cela commence par une analyse des risques adaptée au contexte métier.',
            'Définir les flux sensibles, les niveaux d’accès, les surfaces d’exposition.',
            'Appliquer le principe du moindre privilège et segmenter les responsabilités.',
            '',
            'La sécurité n\'est pas uniquement un pare-feu ou un outil.',
            'Elle se matérialise dans l\'architecture :',
            'gestion des identités, validation des entrées, chiffrement, journalisation, supervision.',
            '',
            'Plus elle est intégrée tôt, plus elle est simple et cohérente.',
            'Ajoutée tardivement, elle devient complexe et fragile.',
            '',
            'Une application sécurisée n\'est pas celle qui n\'a jamais été attaquée.',
            'C\'est celle qui a été pensée pour résister, détecter et réagir.',
            '',
            'La sécurité est une décision d\'architecture, pas un module optionnel.'
        ]
    },
    {
        id: 'article-10',
        title: 'Monolithe ou microservices : choisir selon le contexte',
        image: 'assets/images/articles/Monolithe ou microservices  choisir selon le contexte.png',
        excerpt: 'Monolithe ou microservices : choisir selon le contexte',
        category: 'Architecture logicielle',
        date: '2026-03-10',
        body: [
            '"On part sur des microservices, c\'est plus moderne !"',
            '6 mois plus tard : "Quelqu\'un sait pourquoi le service A n\'arrive plus à parler au service B, et où est passé mon log de transaction ?"',
            'Le mimétisme architectural fait des ravages. Il est temps d\'en parler.',
            '',
            'Le débat monolithe contre microservices est souvent mal posé.',
            '',
            'Sur le terrain, beaucoup de projets choisissent une architecture sans tenir compte du contexte réel.',
            'Le mot microservices arrive souvent avant l\'analyse des besoins.',
            '',
            'Un monolithe bien structuré est souvent pertinent quand :',
            '- une équipe de 2 à 6 développeurs',
            '- un produit encore en construction',
            '- des évolutions fonctionnelles fréquentes',
            '- une exploitation simple à assurer',
            'Résultat : moins d\'infrastructure, moins d\'opérations, plus de vitesse.',
            '',
            'Les microservices deviennent pertinents dans d\'autres situations :',
            '- plus de 15 à 20 développeurs',
            '- plusieurs équipes autonomes',
            '- des domaines métier clairement séparés',
            '- des besoins de montée en charge indépendants',
            'Mais ils introduisent des coûts réels :',
            'déploiements multiples, supervision distribuée, gestion des incidents plus complexe.',
            '',
            'Le choix dépend de facteurs concrets.',
            'Taille de l\'équipe, maturité technique, fréquence des changements, contraintes métier.',
            'Une architecture efficace est celle que l\'organisation peut réellement maîtriser.',
            '',
            'Commencer simple n\'est pas une faiblesse.',
            'Évoluer vers plus de découplage peut être une décision stratégique, pas une obligation.',
            '',
            'L\'architecture doit servir le produit, pas l\'inverse.'
        ]
    }
];
